version: '3.0'

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - docker.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5000:5000
      - 1337:1377
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always    
  postgres:
    container_name: postgres
    image: postgres:15.1
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env
    ports:
      - 5432:5432
    restart: always

volumes:
  pgdata: